apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: yc-clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: timattt@gmail.com
    privateKeySecretRef:
      name: domain-name-secret
    solvers:
      - http01:
          ingress:
            class: nginx