apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: type-6-ingress
  annotations:
    cert-manager.io/cluster-issuer: "yc-clusterissuer"
spec:
  tls:
    - hosts:
        - mipt.io
        - sso.mipt.io
        - grafana.mipt.io
        - pattern.mipt.io
        - messenger.mipt.io
        - grpc.mipt.io
      secretName: domain-name-secret
  ingressClassName: "nginx"
  rules:
    #
    # TYPE-6
    #
    - host: sso.mipt.io
      http:
        paths:
          - path: /public
            pathType: Prefix
            backend:
              service:
                name: type-6
                port:
                  number: 443
    #
    # TYPE-8
    #
    - host: pattern.mipt.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: type-8
                port:
                  number: 443
    #
    # TYPE-11
    #
    - host: grpc.mipt.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: type-11
                port:
                  number: 443
    #
    # TYPE-12
    #
    - host: messenger.mipt.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: type-12
                port:
                  number: 443
    #
    # SERVICES
    #
    - host: grafana.mipt.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 443