apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: type-6-ingress
  annotations:
    cert-manager.io/cluster-issuer: "yc-clusterissuer"
spec:
  tls:
    - hosts:
        - auth-mipt-match.ru
        - mipt-match.ru
        - grafana-shlim-tech.ru
        - prometheus-shlim-tech.ru
        - mipt-study.ru
      secretName: domain-name-secret
  ingressClassName: "nginx"
  rules:
    - host: auth-mipt-match.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: type-6
                port:
                  number: 443
    - host: mipt-match.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: type-7
                port:
                  number: 443
    - host: mipt-study.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: type-8
                port:
                  number: 443
    - host: auth-mipt-match.ru
      http:
        paths:
          - path: /metadata
            pathType: Prefix
            backend:
              service:
                name: type-7-m
                port:
                  number: 443
    - host: auth-mipt-match.ru
      http:
        paths:
          - path: /teaching
            pathType: Prefix
            backend:
              service:
                name: type-8-t
                port:
                  number: 443
    - host: grafana-shlim-tech.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 443
    - host: prometheus-shlim-tech.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: type-6-prom-prometheus-server
                port:
                  number: 80