apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: type-6-ingress
  annotations:
    cert-manager.io/cluster-issuer: "yc-clusterissuer"
spec:
  tls:
    - hosts:
        - service-shlim-tech.ru
        - grafana-shlim-tech.ru
        - prometheus-shlim-tech.ru
      secretName: domain-name-secret
  ingressClassName: "nginx"
  rules:
    #
    # TYPE-6
    #
    - host: service-shlim-tech.ru
      http:
        paths:
          - path: /sso
            pathType: Prefix
            backend:
              service:
                name: type-6
                port:
                  number: 443

    #
    # TYPE-8
    #
    - host: service-shlim-tech.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: type-8
                port:
                  number: 443

    #
    # SERVICES
    #
    - host: grafana-shlim-tech.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 443