apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: type-6-ingress
  annotations:
    cert-manager.io/cluster-issuer: "yc-clusterissuer"
spec:
  tls:
    - hosts:
        - shlimtech.org
        - service.shlimtech.org
        - grafana.shlimtech.org
        - pattern.shlimtech.org
        - rutesil.shlimtech.org
        - messenger.shlimtech.org
      secretName: domain-name-secret
  ingressClassName: "nginx"
  rules:
    #
    # TYPE-6
    #
    - host: service.shlimtech.org
      http:
        paths:
          - path: /sso
            pathType: Prefix
            backend:
              service:
                name: type-6
                port:
                  number: 443
    #
    # TYPE-8
    #
    - host: pattern.shlimtech.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: type-8
                port:
                  number: 443
    #
    # TYPE-9
    #
    - host: rutesil.shlimtech.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: type-9
                port:
                  number: 443
    #
    # TYPE-11
    #
    - host: type-11.shlimtech.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: type-11
                port:
                  number: 443
    #
    # TYPE-12
    #
    - host: messenger.shlimtech.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: type-12
                port:
                  number: 443
    #
    # SERVICES
    #
    - host: grafana.shlimtech.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 443