apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
spec:
  selector:
    matchLabels:
      app: minecraft-deployment
  template:
    metadata:
      labels:
        app: minecraft-deployment
    spec:
      containers:
        - image: itzg/minecraft-server
          name: minecraft
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
              hostPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: ICON
              value: "/data/server-icon.png"
            - name: OPS
              value: "timattt"
            - name: EXISTING_OPS_FILE
              value: "SYNC_FILE_MERGE_LIST"
          resources:
            requests:
              memory: "1000Mi"
            limits:
              memory: "2000Mi"
          volumeMounts:
            - mountPath: /data
              name: minecraft-world
      volumes:
        - name: minecraft-world
          persistentVolumeClaim:
            claimName: minecraft-world-volume