apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  selector:
    app: minecraft-deployment
  ports:
    - port: 25565
      targetPort: 25565
  type: LoadBalancer
  loadBalancerIP: 158.160.129.147
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
