apiVersion: v1
kind: Service
metadata:
  name: type-6
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "7777"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: type-6
  ports:
    - protocol: TCP
      port: 443
      targetPort: 7777