apiVersion: v1
kind: Service
metadata:
  name: type-8-t
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4444"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: type-8-t
  ports:
    - protocol: TCP
      port: 443
      targetPort: 4444