apiVersion: v1
kind: Service
metadata:
  name: type-7-d
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: type-7-d
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8000